export type TeacherModule = { id: string; title: string; topic: string; description: string; sections: Array<{ id: string; title: string; theory: string; practice: string; solution: string }> };

export const starterModules: TeacherModule[] = [
  {
    id: "python-foundations", title: "Python Foundations", topic: "Programming", description: "Build the mental model behind variables, branches, loops, and functions before solving practice problems.",
    sections: [
      { id: "values", title: "Values, variables, and types", theory: "A program transforms values. A variable is a named reference to a value, not a box with a fixed type. In Python, `score = 3` binds the name score to an integer; `score = score + 2` evaluates the right side first, then rebinds score to 5. Choose names that explain the data: `total_marks` is easier to debug than `x`.", practice: "What does this print? `count = 4; count = count + 3; print(count)`", solution: "It prints 7. The expression `count + 3` uses the old value 4, produces 7, then the variable name is rebound to that new value." },
      { id: "control", title: "Decisions and loops", theory: "Use `if` to choose a path from a condition, and a loop to repeat a process. A loop needs a changing state or finite collection; otherwise it never stops. Trace code by writing the value of each variable after every iteration. This is the fastest route from intuition to reliable debugging.", practice: "Write a loop that totals the numbers from 1 through 5. What total should it produce?", solution: "Start with `total = 0`, then for each number from 1 to 5 add it to total. The result is 15. A correct Python form is `for number in range(1, 6): total += number`." },
      { id: "functions", title: "Functions and decomposition", theory: "A function names a reusable transformation. Parameters are inputs; `return` sends a result back to the caller. Good functions do one understandable job, such as `is_even(number)`, rather than mixing input, calculation, and printing. Small functions are easier to test and combine into larger programs.", practice: "Design a function `is_even(number)` and explain what it returns for 14 and 9.", solution: "Use `return number % 2 == 0`. The remainder after division by 2 is 0 for 14, so it returns True; it is 1 for 9, so it returns False." }
    ]
  },
  {
    id: "algorithms-data", title: "Algorithms and Data Structures", topic: "Computer Science", description: "Learn to choose a representation, reason about cost, and turn a vague task into a repeatable algorithm.",
    sections: [
      { id: "complexity", title: "Why complexity matters", theory: "Time complexity describes how work grows as input grows. Constant-time work is O(1); scanning every item once is O(n); nested full scans are often O(n²). Big-O ignores machine speed and small constants so you can compare the shape of solutions. First count the dominant repeated action.", practice: "A program checks every pair in a list of n names for a duplicate. What is its common time complexity?", solution: "O(n²). For each of n names, it may compare against roughly n other names. A set can reduce duplicate detection to expected O(n) by remembering names already seen." },
      { id: "arrays", title: "Arrays, lists, and stacks", theory: "An array/list preserves order and gives fast access by index, while inserting near the front can require shifting many items. A stack follows last-in, first-out: push adds to the top and pop removes the newest item. Match the structure to the operation you perform most often.", practice: "Which structure fits an Undo feature: queue or stack? Explain.", solution: "A stack. The most recent action must be undone first, which is exactly last-in, first-out behaviour." },
      { id: "search", title: "Searching with an invariant", theory: "Binary search works only on sorted data. Keep an invariant: if the target exists, it is inside the current low-to-high interval. Compare the middle item, then discard the half that cannot contain the target. This halves the search interval each step, producing O(log n) time.", practice: "Why is binary search invalid on an unsorted list?", solution: "The middle comparison gives no reliable information about which half contains the target. Without sorted order, discarding half the list can discard the target." }
    ]
  },
  {
    id: "ml-foundations", title: "Machine Learning Foundations", topic: "AI & Machine Learning", description: "Build a responsible first model by separating data, evaluation, and claims about performance.",
    sections: [
      { id: "problem", title: "Frame the learning problem", theory: "Start with the prediction target and the available features. Classification chooses a category, such as spam/not spam; regression predicts a number, such as price. A model cannot learn information missing from its features, and a technically accurate prediction may still be inappropriate if the target encodes unfair or harmful decisions.", practice: "Is predicting whether an email is spam classification or regression?", solution: "Classification, because the output is one of discrete categories: spam or not spam." },
      { id: "split", title: "Train, validation, and test data", theory: "Training data fits model parameters. Validation data guides choices such as model type or settings. Test data is held back until the end to estimate performance on unseen examples. Evaluating repeatedly on the test set leaks information and makes results look better than they are.", practice: "Why should you not tune model settings using the test set?", solution: "Those choices become indirectly fitted to the test set, so it stops being an honest unseen evaluation. Use validation data for tuning and reserve the test set for final measurement." },
      { id: "metrics", title: "Choose metrics that match harm", theory: "Accuracy alone can mislead when classes are imbalanced. Precision asks: when the model predicts positive, how often is it right? Recall asks: of the real positive cases, how many did it find? Choose a metric based on the error that matters most, then inspect examples rather than trusting one number.", practice: "For a disease screening tool, why might recall matter more than accuracy?", solution: "Missing a real disease case can be costly. High recall reduces false negatives, although precision and human review still matter to avoid unnecessary alarms." }
    ]
  }
];

