export type HubTopic = { id: string; title: string; summary: string; realWorld: string; learn: string; practice: string; solution: string; flashcard: { question: string; answer: string }; quiz: { question: string; options: string[]; correct: number; explanation: string } };
export type HubTrack = { title: string; description: string; topicCount: number; topics: HubTopic[] };

const make = (id: string, title: string, summary: string, realWorld: string, learn: string, practice: string, solution: string, question: string, answer: string, options: string[], correct: number, explanation: string): HubTopic => ({ id, title, summary, realWorld, learn, practice, solution, flashcard: { question, answer }, quiz: { question, options, correct, explanation } });

export const hubTracks: HubTrack[] = [
  { title: "Programming Foundations", description: "Turn ideas into dependable programs.", topicCount: 20, topics: [
    make("variables", "Variables and assignment", "Names refer to values; assignment evaluates the right side before rebinding the name.", "Counters power totals, inventory, and analytics.", "In Python, `score = score + 1` reads the current score, creates a new value, then binds score to it. This is different from algebraic equality.", "Trace `count = 4; count = count + 3`. What prints?", "It prints 7: the expression uses 4, produces 7, then count is rebound.", "What happens first in `x = x + 1`?", "The expression on the right is evaluated first.", ["x is erased", "The right side is evaluated", "x becomes a string", "The program always fails"], 1, "Assignment evaluates the expression on the right, then binds the name on the left."),
    make("control-flow", "Conditionals and Boolean logic", "A Boolean condition selects a path; guard clauses make invalid cases explicit.", "Validation and access control depend on complete conditions.", "Use `and`, `or`, and `not` to combine conditions. Place invalid cases first so the normal path remains easy to read.", "A user may submit only when account and payment are both valid. Write the condition.", "Use `has_account and fee_paid`. If either is false, submission should not proceed.", "What does `and` require?", "Both conditions must be true.", ["Either condition", "Both conditions", "Neither condition", "Only numbers"], 1, "A Boolean `and` is true only when each operand is true."),
    make("loops", "Loops and invariants", "Loops repeat a process; invariants are facts that remain true during repetition.", "Batch processing and file parsing rely on correct loop state.", "For a running total, the invariant is: after k items, total equals the sum of those k items. Start at zero and update once per item.", "What invariant describes a running total after processing k values?", "The total equals the sum of exactly the k processed values.", "Why is a loop invariant useful?", "It gives you a fact to check after every iteration.", ["It makes code longer", "It helps reason about correctness", "It removes all bugs", "It replaces tests"], 1, "Invariants make a loop's intended state explicit and testable."),
    make("functions", "Functions and decomposition", "A function is a small named transformation with inputs and an output.", "Services stay maintainable when validation, calculation, and formatting are separate.", "Parameters bring information in; `return` sends a result out. A well-named function should do one understandable job.", "Design `is_even(number)` and state its result for 14 and 9.", "Return `number % 2 == 0`; it gives True for 14 and False for 9.", "What does `return` do?", "It sends a result to the caller.", ["Prints only", "Stops all programs", "Sends a function result", "Creates a loop"], 2, "`return` finishes the function call and provides its result."),
  ] },
  { title: "Discrete Mathematics", description: "Reason precisely about logic, sets, proof, and counting.", topicCount: 18, topics: [
    make("logic", "Propositional logic", "Logic combines statements whose truth can be evaluated.", "Digital circuits, tests, and rules engines are built from logical conditions.", "A proposition is a statement that is true or false. Use truth tables to inspect `and`, `or`, implication, and negation.", "When is `A and B` true?", "Only when both A and B are true.", "What is a proposition?", "A statement that is true or false.", ["A question", "A truth-evaluable statement", "A program", "A number"], 1, "A proposition has a definite truth value."),
    make("induction", "Mathematical induction", "Induction proves a claim for every natural number by linking each case to the next.", "Recursive algorithms and recurrence arguments use the same structure.", "Prove a base case, assume the claim for k, then show that assumption implies the claim for k+1.", "Name the two essential induction steps.", "Base case and inductive step.", "What does the inductive hypothesis assume?", "The statement holds for an arbitrary k.", ["The final answer", "The claim for k", "The claim is false", "A random example"], 1, "The hypothesis assumes the claim at k so you can establish k+1."),
  ] },
  { title: "Algorithms and Data Structures", description: "Choose the right representation and reason about scale.", topicCount: 22, topics: [
    make("complexity", "Complexity and scale", "Big-O describes the growth of dominant work as input grows.", "It decides whether a feature works for 100 records or 10 million.", "O(n) scans items once; O(n squared) often compares every pair; O(log n) repeatedly halves a valid search space.", "A nested loop compares every pair of n names. What is the common complexity?", "O(n squared). A set can often reduce duplicate detection to expected O(n).", "What does O(n) describe?", "Work that grows roughly linearly with input size.", ["Constant work", "Linear growth", "Always slow", "No memory use"], 1, "O(n) means the dominant operation is done once per input item."),
    make("binary-search", "Binary search", "Binary search discards half of a sorted search interval at a time.", "Databases and autocomplete use ordered/indexed data for fast lookup.", "Maintain the invariant that if the target exists, it lies in the current low-to-high interval. Compare the middle, then remove the impossible half.", "Why is binary search invalid on unsorted data?", "The middle comparison gives no reliable direction, so discarding half may discard the target.", "What prerequisite does binary search need?", "Sorted data.", ["A queue", "Sorted data", "A GPU", "Random input"], 1, "Order makes a middle comparison informative."),
    make("hash-maps", "Hash maps", "Hash maps associate keys with values for fast average lookup.", "Counting events, caching, and indexing use key-value lookup constantly.", "A hash function directs a key toward a location. Collisions need handling, but a dictionary still gives expected constant-time access in common cases.", "How would you count words in a document?", "Use a dictionary and update `counts[word] = counts.get(word, 0) + 1`.", "What does a hash map store?", "Key-value associations.", ["Only sorted numbers", "Key-value pairs", "A single stack", "Images only"], 1, "A hash map maps a distinct key to an associated value."),
    make("arrays", "Arrays and indexing", "An array keeps values in a defined order, so a position can be read directly.", "Timelines, image pixels, sensor samples, and game boards are naturally ordered collections.", "Indexes begin at zero in Python. Reading item i is constant time, but inserting at the front shifts later items, which costs linear time.", "For `scores = [7, 9, 4]`, what are `scores[0]` and `scores[-1]`?", "They are 7 and 4. Index zero is the first item; negative one is the final item in Python.", "What is the usual cost of reading an array item by index?", "Constant time.", ["O(1)", "O(n)", "O(n squared)", "Impossible"], 0, "An array can calculate the location of an indexed item directly."),
    make("sorting", "Sorting and comparison", "Sorting establishes an order so later operations can reason efficiently about data.", "Leaderboards, date feeds, ranking, and database query plans all depend on ordering.", "Comparison sorts repeatedly ask which of two items comes first. A practical built-in sort is usually preferable; learn elementary sorts to understand invariants, not to replace mature libraries.", "Why is it useful to sort records by date before searching a date range?", "Dates become contiguous, so binary search can find the boundaries instead of scanning every record.", "What does sorting create?", "A consistent order based on a comparison rule.", ["Randomness", "A comparison-based order", "A hash collision", "More memory only"], 1, "Sorting places values into an order that later algorithms can exploit."),
    make("recursion", "Recursion and base cases", "Recursion solves a problem by reducing it to smaller instances of the same problem.", "Folder traversal, parsers, tree search, and divide-and-conquer algorithms use recursive structure.", "Every recursive function needs a base case that stops and a reduction that moves measurably toward it. Trace one small input by hand before trusting it.", "Give a recursive definition of factorial for non-negative n.", "Base: factorial(0) = 1. Reduction: factorial(n) = n × factorial(n - 1) for n > 0.", "What prevents infinite recursion?", "A reachable base case.", ["A larger input", "A reachable base case", "More variables", "A print statement"], 1, "The base case ends the chain of self-calls."),
    make("stacks-queues", "Stacks and queues", "Stacks use last-in-first-out order; queues use first-in-first-out order.", "Undo history is stack-shaped; print jobs, support tickets, and breadth-first search are queue-shaped.", "Pick the data structure from the order of service. A stack pushes and pops one end. A queue adds at the back and removes from the front.", "Which structure models people waiting in a line, and why?", "A queue: the first person to arrive should be the first served (FIFO).", "What order does a stack use?", "Last in, first out.", ["First in, first out", "Last in, first out", "Sorted only", "Random"], 1, "A stack removes the most recently added item first."),
    make("trees", "Trees and hierarchical data", "A tree connects nodes in parent-child relationships without cycles; a binary search tree also maintains an ordering rule.", "File systems, page outlines, syntax trees, and organisation charts are hierarchical.", "Tree traversal means choosing a systematic visit order. In a binary search tree, an in-order traversal visits keys in sorted order because all left keys precede the node and all right keys follow it.", "Why does in-order traversal of a valid binary search tree produce sorted keys?", "It visits every smaller left-subtree key, then the node, then every larger right-subtree key.", "What is a tree good at representing?", "Hierarchy.", ["Only matrices", "Hierarchy", "Network packets only", "A single scalar"], 1, "Parents and children naturally represent nested relationships."),
    make("graphs", "Graphs and breadth-first search", "Graphs model entities and relationships; breadth-first search explores in layers from a start node.", "Maps, social connections, prerequisites, and network routing are graph problems.", "BFS uses a queue and marks nodes when discovered. In an unweighted graph, the first time it reaches a node is through a shortest number-of-edges path.", "Why mark a node when it is added to the BFS queue?", "It prevents duplicate enqueues and guarantees each node is processed once.", "Which structure does BFS use?", "A queue.", ["Stack", "Queue", "Hash only", "Matrix only"], 1, "A queue preserves the layer-by-layer order BFS requires."),
    make("dynamic-programming", "Dynamic programming", "Dynamic programming saves answers to overlapping subproblems instead of recomputing them.", "Autocomplete, sequence alignment, planning, and optimisation often reuse smaller answers.", "First define the state precisely: what does dp[i] mean? Then write a recurrence, base cases, and an evaluation order. Memorisation caches top-down calls; tabulation fills a table bottom-up.", "For climbing 1 or 2 steps at a time, what recurrence counts ways to reach step n?", "ways(n) = ways(n - 1) + ways(n - 2), with ways(0) = 1 and ways(1) = 1. The final move came from one of those two states.", "When is dynamic programming appropriate?", "When subproblems overlap and optimal structure can be reused.", ["When all answers are random", "When subproblems overlap", "Only for arrays", "Only for graphics"], 1, "Saving repeated subproblem answers is the central DP idea."),
  ] },
  { title: "Systems, Web, and Data", description: "See what happens beneath code and across a network.", topicCount: 24, topics: [
    make("binary", "Bits, bytes, and binary", "Computers represent information with bits; bytes are groups of eight bits.", "Storage, networks, colour, and machine instructions all use binary representation.", "Binary is base 2. Place values double from right to left: 1, 2, 4, 8, and so on.", "Convert binary 1011 to decimal.", "8 + 0 + 2 + 1 = 11.", "How many bits are in a byte?", "Eight.", ["2", "4", "8", "16"], 2, "A byte conventionally contains eight bits."),
    make("http", "HTTP and APIs", "HTTP defines how clients request resources and servers respond.", "Web apps and mobile apps use APIs to exchange structured data.", "A request has a method, URL, headers, and sometimes a body. A response has a status code, headers, and a body, often JSON.", "What is a 404 response communicating?", "The requested resource was not found.", "What is an API?", "An interface for software to communicate.", ["A file type", "A hardware chip", "A software interface", "A database row"], 2, "An API defines a way for programs to request or exchange capabilities/data."),
  ] },
  { title: "Math for AI and Machine Learning", description: "Use linear algebra, probability, and evaluation to think clearly about models.", topicCount: 20, topics: [
    make("vectors", "Vectors and dot products", "Vectors are ordered numeric lists; dot products measure aligned components.", "Similarity search and neural layers rely on vector operations.", "Multiply matching components and add them. For [2,3] dot [4,-1], calculate 2×4 + 3×-1.", "Compute [2,3] dot [4,-1].", "8 - 3 = 5.", "What does a dot product do?", "It multiplies matching components and sums them.", ["Sorts values", "Multiplies and sums matching entries", "Deletes a vector", "Creates a string"], 1, "The dot product combines corresponding components into one scalar."),
    make("matrices", "Matrices and transformations", "A matrix is a table of numbers that transforms an input vector into an output vector through weighted combinations.", "Graphics, image transforms, and neural-network layers are repeated matrix transformations.", "An m by n matrix takes an n-dimensional input and produces an m-dimensional output. Dimensions are not decoration: they prove whether multiplication is defined.", "A 2 by 3 matrix multiplies what length vector, and produces what length vector?", "It needs a length-3 input because it has 3 columns, and produces a length-2 output because it has 2 rows.", "What must match for matrix-vector multiplication?", "The matrix column count must equal the vector length.", ["The row count and vector length", "The column count and vector length", "All values must be positive", "Nothing"], 1, "Each matrix row takes a weighted combination of all input coordinates, so its number of columns must match the input length."),
    make("derivatives", "Derivatives as rates of change", "A derivative measures how an output changes when its input changes by a very small amount.", "Velocity, marginal cost, and model sensitivity are all rate-of-change questions.", "Zoom into a smooth graph until it looks like a line. The slope of that local line is the derivative. Always carry units with your interpretation.", "If s(t) = t squared, what is the derivative at t = 3?", "The derivative is 2t, so it is 6 at t = 3. If s is metres and t is seconds, the unit is metres per second.", "What does a derivative represent locally?", "A rate of change or slope.", ["A list length", "A local rate of change", "A random sample", "A database join"], 1, "A derivative captures the slope of a function near one input value."),
    make("gradient-descent", "Gradients and gradient descent", "A gradient collects rate-of-change information for a function with many inputs; moving opposite it can reduce a loss.", "Linear regression and neural networks are trained through repeated gradient-based updates.", "Imagine descending a foggy hill. The gradient points steepest uphill, so a cautious step in the opposite direction decreases height. The learning rate chooses how cautious the step is.", "Why can an overly large learning rate fail even with the correct gradient?", "It can leap past a low point, bounce between sides, or diverge. Direction and step size both matter.", "What does the learning rate control?", "The size of each update step.", ["The data type", "The number of classes", "The update step size", "The test set"], 2, "The learning rate scales how far parameters move on each gradient update."),
    make("probability", "Conditional probability", "Conditional probability measures an event after restricting to a condition.", "Screening, fraud, and A/B tests need base-rate aware conditional reasoning.", "P(A given B) asks about A only among outcomes where B happened. State the population before calculating.", "30 students use Python; 18 also use Git. What is P(Git given Python)?", "18/30 = 0.6 because only Python users are now in the sample space.", "What changes under conditional probability?", "The sample space is restricted by the condition.", ["The programming language", "The sample space", "All facts disappear", "Nothing"], 1, "Conditioning filters the possible outcomes to those where the condition holds."),
    make("expectation", "Expectation and variance", "Expectation is a long-run weighted average; variance measures how spread out outcomes are around that average.", "Forecasting and model-risk decisions need both an average and a sense of uncertainty.", "Expectation is the balance point of possible outcomes. Variance asks whether outcomes cluster tightly around that balance or vary widely.", "What is the expectation of a fair six-sided die?", "Add 1 through 6 to get 21, then divide by 6: 3.5. You do not roll 3.5; it is the long-run average.", "Can an expectation be a value that never occurs?", "Yes, such as 3.5 for a fair die.", ["Never", "Only for ML", "Yes", "Only after sorting"], 2, "Expectation describes a weighted average, not necessarily one possible outcome."),
    make("evaluation", "Train, validation, and test", "Separate data prevents a model evaluation from being tuned to its own exam.", "Honest evaluation protects deployment decisions in real systems.", "Fit parameters on training data; tune choices on validation data; reserve test data for a final unseen estimate.", "Why should test data not guide repeated tuning?", "It leaks into the selection process and makes final performance look overly optimistic.", "What should test data be used for?", "Final generalisation evaluation.", ["Daily training", "Final evaluation", "Feature creation", "Password storage"], 1, "The test set is held out for the final honest performance estimate."),
    make("precision-recall", "Precision, recall, and real harm", "Precision asks whether positive predictions are trustworthy; recall asks whether real positives were found.", "Medical screening, moderation, and fraud detection each value errors differently.", "A wide net catches more cases (recall) but may bring more false alarms. A narrow net can be more precise but miss real cases. Metrics express a trade-off, not a moral answer.", "Why might recall matter especially in early disease screening?", "Missing a real case can be costly, so the process should find as many genuine cases as possible. Follow-up review can manage false positives.", "What does recall measure?", "The fraction of real positive cases found.", ["Correct negative cases", "Positive predictions that are right", "Real positives found", "Average model speed"], 2, "Recall is true positives divided by all actual positives."),
  ] },
];


